language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - wget
    - zsh
script:
- cargo build --verbose
- cargo test --verbose
notifications:
  email:
    on_success: never
    on_failure: always

before_deploy: "bash package.sh"
deploy:
  provider: releases
  api_key:
    secure: RXDJOacB1it3RgvCf2LxxGlQfov6QlCltxnYpuMU+TXDEXdpbEbybLLGsBnWx0jc+cE1PWcVrEZvTP71FM5JSOfgkUjvCKkhK4RKwj+wdYOSd0WyIV0uOI3NLqQHKLu37x5Q8+4Ch5h3t9/qfL3rIh2VACWVtHr4LGTapboZMI/CdBxJyUMfPviflKQEYgUPzs7i7ZQVMZy4ugJ7ASLPbie2dhDgmfNLlANnrM/HrzTmaU1xPKV8g2B1itaVowa9tmcRd1porXfTzhQutkU+CBNIhJ/CiPlrYSPXQ+iRaEfwQmamzwGE5FcRBe95qbLJbnQDEqws05BNQSwc9eQHVGkm7uUyQLewAIQmGS/VnAT+oUSJ5fghtsqmVIpHMnXJwMcXLJ30Nv3KOEsu7t9GDqMp0IpB4Amoi7cbrBMGky87TPboJnFlqbHJFhGiYbcCnAO4vsOkPBE2OPxjiiyp5ODXoKqPMoFA7TQ6d5yVIOujsiMmGmYIpfTZbRprKHfo/2gGwPKDEST4gKEzV7GnrdjUnffTOGE30wxS0S4iM8PjsziBXjhDH3oBWziy5UdnZZbBAVnku0SCQltoLorT7jBeF6Ccgz5PoUybIAngSAUbVD2RCdC2R/7fYU9jzj29onpXGQ8h9LyFX+Rol6+TGhQgItETJlX7e/S/rmBJZbY=
  file:
    - "./target/x86_64-unknown-linux-musl/release/dotcopter"
    - "./target/x86_64-unknown-linux-musl/release/dotcopter.deb"
    - "./target/x86_64-unknown-linux-musl/release/dotcopter.rpm"
  on:
    tags: true
    rust: stable
