language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - wget
      - zsh

script:
  - cargo build --verbose
  - cargo test --verbose

notifications:
  email:
    on_success: never
    on_failure: always
