name: Release

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build musl
      run: bash -c "export TRAVIS=true; bash package.sh"
    - name: Upload
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: './target/x86_64-unknown-linux-musl/release/dotcopter ./target/x86_64-unknown-linux-musl/release/dotcopter.deb ./target/x86_64-unknown-linux-musl/release/dotcopter.rpm'
